server:
  port: 9999


spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ******
            clientSecret: *****
          google:
            clientId: ******
            clientSecret: *****

